:root {

<?php if (!empty(cmb2_get_option('cmb2_key_box_colors', 'cmb2_field_id_example_color'))) {
    $example_color_hex = cmb2_get_option('cmb2_key_box_colors', 'cmb2_field_id_example_color');
    $example_color_hsl = Keystone_Colors::hexToHsl($example_color_hex);
    ?>

    --keystone-example-color-h: <?php echo $example_color_hsl['H'] ?>;
    --keystone-example-color-s: <?php echo $example_color_hsl['S'] . '%' ?>;
    --keystone-example-color-l: <?php echo $example_color_hsl['L'] . '%' ?>;
    --keystone-example-color:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),var(--keystone-example-color-l));--keystone-example-color-l1:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 5%));--keystone-example-color-l2:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 10%));--keystone-example-color-l3:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 15%));--keystone-example-color-l4:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 20%));--keystone-example-color-l5:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 25%));--keystone-example-color-l6:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 30%));--keystone-example-color-l7:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 35%));--keystone-example-color-l8:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) + 40%));--keystone-example-color-d1:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 5%));--keystone-example-color-d2:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 10%));--keystone-example-color-d3:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 15%));--keystone-example-color-d4:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 20%));--keystone-example-color-d5:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 25%));--keystone-example-color-d6:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 30%));--keystone-example-color-d7:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 35%));--keystone-example-color-d8:hsl(var(--keystone-example-color-h),var(--keystone-example-color-s),calc(var(--keystone-example-color-l) - 40%));
   <?php } ?>
}